services:
  app:
    image: ghcr.io/thinkinwalk/infinite-canvas:v0.19.2
    container_name: infinite-canvas
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3000"
      - "127.0.0.1:3002:3000"
    restart: unless-stopped
